### ISSUE TITLE
 Touchpad üzerinde scrollarken sayfaların değişmesi

### ISSUE THREAD

**Issue by zeynepcambaz** [havascxistanbul/ycc-remastered#4]
Touchpad üzerinde sağa veya sola kaydırma hareketi yaptığımızda sayfanın diğer sayfaya geçmesi

**Comment by ravevy** [comment]
Touchpad üzerinde çift parmak ile aşağı ve yukarı scrollayarak sayfa geçişi sağlanıyor. Bu noktada sağa ve sola kaydırma hareketi kullanıcı deneyimi açısından kafa karıştırıcı olabilir. Dolayısıyla bu özelliğin eklenmemesinin daha doğru olacağını düşünüyorum.
